SELECT BOOK_ID, B.AUTHOR_NAME AS 'AUTHOR_NAME', date_format(PUBLISHED_DATE,'%Y-%m-%d') AS 'PUBLISHED_DATE'
FROM BOOK AS A JOIN AUTHOR AS B ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE CATEGORY LIKE '경제'
ORDER BY PUBLISHED_DATE ASC;